# This is a basic workflow to help you get started with Actions

name: Generate Documentation

# Controls when the action will run. 
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
      runs-on: ubuntu-latest     
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENCE_2019_4_12F1 }}
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      - uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          buildMethod: UnityEditor.SyncVS.SyncSolution
          targetPlatform: StandaloneWindows
          
      - name: Build
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: Documentation/docfx.json

      # Upload the generated documentation
      - name: Upload site artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site # Must equals the 'build.dest' value on your docfx.json
          
    # Deploy the generated documentation to the gh-pages branch
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true

      # Download the generated documentation
      - name: Download site artifact
        uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site
                  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site