name: CI
# Controls when the action will run. 
on:
  push:
    tags:
    - '*'
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  split-upm:
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Branch name
      run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Build base image
      run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
      env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    - name: split upm branch
      run: |
        git subtree split -P "$PKG_ROOT" -b upm
        git push -u origin upm
      env:
        PKG_ROOT: "Assets/Unity_Extensions"
